name: Install Gobuster

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install Gobuster
        run: go install github.com/OJ/gobuster/v3@latest

      - name: Verify Gobuster installation
        run: |
          curl -s https://raw.githubusercontent.com/mehrankazemi1122/temp_repo_automata/main/admin.txt > admin.txt
          curl -s https://raw.githubusercontent.com/mehrankazemi1122/temp_repo_automata/main/sites.txt > sites.txt
          cat sites.txt | while read -r line;do gobuster fuzz -u $line -w admin.txt -b 404 --useragent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0" -k -z



          
